CONDA_DEFAULT_ENV=base
CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe
CONDA_PREFIX=C:\ProgramData\Anaconda3
CONDA_PROMPT_MODIFIER=(base) 
CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
CONDA_SHLVL=1
PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3\condabin;C:\app\product\11.2.0\client_1;C:\T2000Maintenance\bin;C:\MBTools\sys;C:\Perl\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\MBTools;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\ICMTools\bin;C:\T2000\InstallSets\CMT_AT30425_AMD64_R1.0\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Users\ittayeya\bin;C:\Users\ittayeya\AppData\Local\Microsoft\WindowsApps;C:\Users\ittayeya\.dotnet\tools;C:\Users\ittayeya\AppData\Local\Programs\Microsoft VS Code\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROMPT=(base) $P$G
PSMODULEPATH=C:\Users\ittayeya\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PYTHONIOENCODING=utf-8
PYTHONUNBUFFERED=1
PYTHONUTF8=1
CONDA_ROOT=C:\ProgramData\Anaconda3
_CONDA_OLD_CHCP=437
VSCODE_L10N_BUNDLE_LOCATION=